spring:
  jpa:
    open-in-view: 'false'
  profiles:
    active: ${APP_PROFILE:test}

security:
  oauth2:
    client:
      client-secret: ${CLIENT_SECRET:dscatalog123}
      client-id: ${CLIENT_ID:dscatalog}

jwt:
  secret: ${JWT_SECRET:MY-JWT-SECRET}
  duration: ${JWT_DURATION:86400}
